// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const baseId = 'isxqxbysfsdyhmjcxfsm';
const proxyBaseUrl = `https://kz.proxy.atiks.org/supabase/${baseId}`;

const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxb2R0c3dnZnp2eHJvdHR6dnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTM5OTMsImV4cCI6MjA1OTYyOTk5M30.NSoaX-SNaTB5_rhGm_VC-RF4T7RnXFHkpgZ7O4qHX5A';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(proxyBaseUrl, supabaseKey);
