
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const baseId = 'isxqxbysfsdyhmjcxfsm';
const proxyBaseUrl = `https://kz.proxy.atiks.org/supabase/${baseId}`;

const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzeHF4YnlzZnNkeWhtamN4ZnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTUzNjUsImV4cCI6MjA1ODIzMTM2NX0.OSmh005slZWbm1BwEPsDDYKzkjwZgPs4q4VoRLXs0H0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(proxyBaseUrl, supabaseKey, {
  global: {
    // Увеличиваем таймауты для всех запросов
    fetch: (url, options = {}) => {
      return fetch(url, {
        ...options,
        // Устанавливаем таймаут в 30 секунд для всех запросов
        signal: AbortSignal.timeout(30000),
      }).catch((error) => {
        // Если запрос был отменен из-за таймаута, бросаем более понятную ошибку
        if (error.name === 'AbortError' || error.name === 'TimeoutError') {
          throw new Error('Request timeout: Server took too long to respond');
        }
        throw error;
      });
    },
  },
  // Настройки для функций
  functions: {
    // Увеличиваем таймаут для Edge функций до 60 секунд
    timeout: 60000,
  },
});
